# Cloud Configuration for Streamlit Cloud Deployment
# This file contains all configuration settings for cloud deployment

cloud:
  # Database Configuration
  database:
    type: "sqlite"
    path: "./cloud_data.db"
    max_connections: 10
    timeout: 30
    memory_limit: "256MB"
  
  # Vector Store Configuration
  vector_store:
    type: "chromadb"
    storage: "memory"
    cache_size: 1000
    embedding_model: "all-MiniLM-L6-v2"
    chunk_size: 1000
    chunk_overlap: 200
  
  # Agent Configuration
  agents:
    max_concurrent: 5
    timeout: 30
    memory_limit: "512MB"
    cleanup_interval: 300  # 5 minutes
  
  # Monitoring Configuration
  monitoring:
    enabled: true
    log_level: "INFO"
    metrics_interval: 60
    health_check_interval: 30
  
  # Streamlit Cloud Configuration
  streamlit:
    max_upload_size: 200  # MB
    enable_xsrf_protection: false
    enable_cors: false
    gather_usage_stats: false
    server_port: 8501
    server_address: "0.0.0.0"
  
  # Deployment Configuration
  deployment:
    auto_deploy: true
    validate_before_deploy: true
    run_tests: true
    monitor_deployment: true
    deployment_timeout: 300  # 5 minutes

# Required Files for Cloud Deployment
required_files:
  - "ai_help_agent_streamlit_cloud.py"
  - "streamlit_app.py"
  - "requirements_cloud.txt"
  - ".streamlit/config.toml"
  - "cloud_adapters/__init__.py"
  - "cloud_adapters/sqlite_adapter.py"
  - "cloud_adapters/cloud_chromadb.py"
  - "cloud_adapters/cloud_agent_manager.py"
  - "config/cloud_config.yml"
  - "README.md"
  - "STREAMLIT_CLOUD_DEPLOYMENT_GUIDE.md"
  - "cloud_structure.md"

# Required Directories
required_directories:
  - "cloud_adapters"
  - "cloud_utils"
  - "config"
  - "static"
  - "data"
  - "tests"

# Cloud Requirements
requirements:
  # File Size Limits
  max_file_size: 10485760  # 10MB
  max_repo_size: 104857600  # 100MB
  max_requirements_size: 10240  # 10KB
  
  # Dependencies
  allowed_packages:
    - "streamlit"
    - "pandas"
    - "numpy"
    - "plotly"
    - "requests"
    - "PyYAML"
    - "aiofiles"
    - "asyncio"
    - "sqlite3"
    - "hashlib"
    - "json"
    - "logging"
    - "pathlib"
    - "typing"
    - "datetime"
    - "time"
    - "random"
    - "re"
    - "collections"
    - "itertools"
  
  # Prohibited Packages (too large or incompatible)
  prohibited_packages:
    - "torch"
    - "transformers"
    - "sentence-transformers"
    - "postgresql"
    - "psycopg2"
    - "tensorflow"
    - "scikit-learn"
    - "matplotlib"
    - "seaborn"
    - "jupyter"
    - "notebook"
    - "ipython"
    - "dask"
    - "vaex"
    - "modin"
    - "rapids"
    - "cupy"
    - "numba"
    - "cython"
    - "pybind11"

# Testing Configuration
testing:
  # Unit Tests
  unit_tests:
    - "tests/test_cloud_deployment.py"
    - "tests/test_cloud_adapters.py"
    - "tests/test_streamlit_cloud.py"
  
  # Integration Tests
  integration_tests:
    - "tests/test_end_to_end.py"
    - "tests/test_performance.py"
  
  # Validation Tests
  validation_tests:
    - "scripts/validate_cloud_requirements.py"
    - "scripts/test_imports.py"
  
  # Test Timeout
  timeout: 300  # 5 minutes

# Performance Requirements
performance:
  # Response Time Limits
  max_response_time: 5.0  # seconds
  max_initialization_time: 30.0  # seconds
  
  # Memory Limits
  max_memory_usage: "1GB"
  max_cpu_usage: 80  # percentage
  
  # Resource Optimization
  lazy_loading: true
  caching_enabled: true
  cleanup_enabled: true

# Security Configuration
security:
  # Environment Variables
  required_env_vars:
    - "STREAMLIT_SERVER_PORT"
    - "STREAMLIT_SERVER_ADDRESS"
    - "STREAMLIT_SERVER_MAX_UPLOAD_SIZE"
  
  # Optional Environment Variables
  optional_env_vars:
    - "OPENAI_API_KEY"
    - "LANGSMITH_API_KEY"
    - "STREAMLIT_CLOUD_URL"
  
  # Security Settings
  enable_https: true
  enable_cors: false
  enable_xsrf_protection: false
  allow_file_uploads: true
  max_upload_size: 200  # MB

# Monitoring and Logging
monitoring:
  # Logging Configuration
  logging:
    level: "INFO"
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    file: "cloud_deployment.log"
    max_size: "10MB"
    backup_count: 5
  
  # Metrics Collection
  metrics:
    enabled: true
    interval: 60  # seconds
    retention: 24  # hours
  
  # Health Checks
  health_checks:
    enabled: true
    interval: 30  # seconds
    timeout: 10  # seconds
    endpoints:
      - "/health"
      - "/status"
      - "/metrics"

# Error Handling
error_handling:
  # Error Recovery
  auto_recovery: true
  max_retries: 3
  retry_delay: 5  # seconds
  
  # Error Reporting
  error_reporting: true
  error_logging: true
  error_notification: false
  
  # Graceful Degradation
  graceful_degradation: true
  fallback_mechanisms: true

# Deployment Workflow
deployment_workflow:
  # Pre-deployment Steps
  pre_deployment:
    - "validate_environment"
    - "install_dependencies"
    - "run_validation_tests"
    - "run_functional_tests"
    - "prepare_cloud_repository"
  
  # Deployment Steps
  deployment:
    - "commit_changes"
    - "push_to_remote"
    - "trigger_deployment"
    - "monitor_deployment"
  
  # Post-deployment Steps
  post_deployment:
    - "verify_deployment"
    - "run_smoke_tests"
    - "update_documentation"
    - "notify_stakeholders"

# Success Criteria
success_criteria:
  # Technical Success
  technical:
    deployment_success_rate: 100  # percentage
    response_time: 5.0  # seconds
    uptime: 99.9  # percentage
    error_rate: 1.0  # percentage
  
  # User Experience Success
  user_experience:
    functionality_score: 95  # percentage
    performance_score: 90  # percentage
    reliability_score: 95  # percentage
    usability_score: 90  # percentage
  
  # Business Success
  business:
    adoption_rate: 70  # percentage
    satisfaction_score: 4.5  # out of 5
    value_delivery: 80  # percentage
    scalability_score: 85  # percentage

# Documentation Requirements
documentation:
  # Required Documentation
  required:
    - "README.md"
    - "STREAMLIT_CLOUD_DEPLOYMENT_GUIDE.md"
    - "cloud_structure.md"
    - "API_DOCUMENTATION.md"
  
  # Documentation Standards
  standards:
    min_readme_size: 1000  # bytes
    min_api_docs_size: 2000  # bytes
    include_examples: true
    include_screenshots: true
    include_troubleshooting: true

# Maintenance and Updates
maintenance:
  # Update Schedule
  updates:
    dependencies: "weekly"
    security_patches: "immediate"
    feature_updates: "monthly"
    documentation: "as_needed"
  
  # Backup Strategy
  backup:
    enabled: true
    frequency: "daily"
    retention: "30_days"
    location: "cloud_storage"
  
  # Monitoring
  monitoring:
    enabled: true
    alerts: true
    reporting: "weekly"
    optimization: "monthly" 