# GitHub Auto Update Configuration

# Source directory containing the code to sync
source_directory: "."

# Target repository path (local clone of the target repository)
target_repository_path: "../System-Reference"

# GitHub repository URL
repository_url: "https://github.com/Kausiukas/System-Reference.git"

# GitHub personal access token (for API access)
github_token: "${GITHUB_TOKEN}"

# File patterns to include in sync
include_patterns:
  - "src/**/*.py"
  - "src/**/*.js"
  - "src/**/*.ts"
  - "src/**/*.yaml"
  - "src/**/*.yml"
  - "src/**/*.json"
  - "docs/**/*.md"
  - "config/**/*.yaml"
  - "config/**/*.yml"
  - "scripts/**/*.py"
  - "scripts/**/*.sh"
  - "k8s/**/*.yaml"
  - "terraform/**/*.tf"
  - "docker/**/*"
  - "*.md"
  - "*.txt"
  - "*.yml"
  - "*.yaml"
  - "Dockerfile*"
  - "docker-compose*.yml"
  - "requirements.txt"
  - "package.json"
  - "README.md"

# File patterns to exclude from sync
exclude_patterns:
  - "**/__pycache__/**"
  - "**/*.pyc"
  - "**/*.pyo"
  - "**/*.pyd"
  - "**/.git/**"
  - "**/node_modules/**"
  - "**/venv/**"
  - "**/.env"
  - "**/.env.local"
  - "**/.env.production"
  - "**/logs/**"
  - "**/temp/**"
  - "**/tmp/**"
  - "**/.DS_Store"
  - "**/Thumbs.db"
  - "**/*.log"
  - "**/coverage/**"
  - "**/.pytest_cache/**"
  - "**/.mypy_cache/**"

# Directories to create in target repository
directories:
  - "src"
  - "src/core"
  - "src/processors"
  - "src/ai"
  - "src/ui"
  - "src/utils"
  - "docs"
  - "docs/architecture"
  - "docs/components"
  - "docs/deployment"
  - "docs/api"
  - "docs/troubleshooting"
  - "config"
  - "scripts"
  - "tests"
  - "docker"
  - "k8s"
  - "terraform"
  - "monitoring"
  - "logs"

# Commit message templates
commit_messages:
  auto_update: "Auto-update: {timestamp}"
  feature: "feat: {description}"
  fix: "fix: {description}"
  docs: "docs: {description}"
  refactor: "refactor: {description}"
  test: "test: {description}"
  chore: "chore: {description}"

# Release configuration
release:
  auto_version: true
  version_format: "YYYY.MM.DD"
  prerelease: false
  draft: false
  generate_notes: true

# Backup configuration
backup:
  enabled: true
  backup_dir: "backups"
  max_backups: 10
  compress_backups: true

# Logging configuration
logging:
  level: "INFO"
  file: "github_auto_update.log"
  max_size: "10MB"
  backup_count: 5

# Notification configuration
notifications:
  email:
    enabled: false
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    username: "${EMAIL_USERNAME}"
    password: "${EMAIL_PASSWORD}"
    recipients: []
  
  slack:
    enabled: false
    webhook_url: "${SLACK_WEBHOOK_URL}"
    channel: "#system-reference"
  
  discord:
    enabled: false
    webhook_url: "${DISCORD_WEBHOOK_URL}"

# Security configuration
security:
  validate_files: true
  check_file_permissions: true
  scan_for_secrets: true
  allowed_file_types:
    - ".py"
    - ".js"
    - ".ts"
    - ".yaml"
    - ".yml"
    - ".json"
    - ".md"
    - ".txt"
    - ".sh"
    - ".tf"
    - "Dockerfile"

# Performance configuration
performance:
  max_file_size: "10MB"
  parallel_processing: true
  max_workers: 4
  timeout: 300  # seconds

# Error handling
error_handling:
  max_retries: 3
  retry_delay: 5  # seconds
  continue_on_error: false
  rollback_on_failure: true 