# Monitoring and Alerting Configuration

prometheus:
  scrape_interval: 15s
  evaluation_interval: 15s

  # Alert manager rules
  rule_files:
    - "alerts.yml"

  scrape_configs:
    - job_name: 'client_profile_builder'
      static_configs:
        - targets: ['localhost:8501']
      metrics_path: '/metrics'

    - job_name: 'chromadb'
      static_configs:
        - targets: ['localhost:8000']

    - job_name: 'node_exporter'
      static_configs:
        - targets: ['localhost:9100']

alertmanager:
  global:
    resolve_timeout: 5m
    slack_api_url: '${SLACK_WEBHOOK_URL}'

  route:
    group_by: ['alertname', 'cluster', 'service']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    receiver: 'slack-notifications'

  receivers:
    - name: 'slack-notifications'
      slack_configs:
        - channel: '#alerts'
          title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
          text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"

metrics:
  # Application metrics
  - name: client_profile_builder_requests_total
    type: counter
    help: Total number of requests processed
    labels:
      - endpoint
      - status

  - name: client_profile_builder_request_duration_seconds
    type: histogram
    help: Request duration in seconds
    buckets: [0.1, 0.5, 1.0, 2.0, 5.0]
    labels:
      - endpoint

  - name: client_profile_builder_emails_processed_total
    type: counter
    help: Total number of emails processed
    labels:
      - status

  - name: client_profile_builder_email_processing_duration_seconds
    type: histogram
    help: Email processing duration in seconds
    buckets: [1.0, 5.0, 10.0, 30.0, 60.0]

  - name: client_profile_builder_profiles_created_total
    type: counter
    help: Total number of client profiles created

  - name: client_profile_builder_api_calls_total
    type: counter
    help: Total number of external API calls
    labels:
      - api
      - status

  # Resource metrics
  - name: client_profile_builder_memory_usage_bytes
    type: gauge
    help: Current memory usage in bytes

  - name: client_profile_builder_cpu_usage_percent
    type: gauge
    help: Current CPU usage percentage

  # Business metrics
  - name: client_profile_builder_sales_stage_count
    type: gauge
    help: Number of clients in each sales stage
    labels:
      - stage

  - name: client_profile_builder_email_review_status
    type: gauge
    help: Number of emails in each review status
    labels:
      - status

alerts:
  # Performance alerts
  - alert: HighRequestLatency
    expr: rate(client_profile_builder_request_duration_seconds_sum[5m]) > 2
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: High request latency
      description: Average request latency is above 2 seconds

  - alert: HighErrorRate
    expr: rate(client_profile_builder_requests_total{status="error"}[5m]) > 0.1
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: High error rate
      description: Error rate is above 10%

  # Resource alerts
  - alert: HighMemoryUsage
    expr: client_profile_builder_memory_usage_bytes > 1e9
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: High memory usage
      description: Memory usage is above 1GB

  - alert: HighCPUUsage
    expr: client_profile_builder_cpu_usage_percent > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: High CPU usage
      description: CPU usage is above 80%

  # Business alerts
  - alert: LowEmailReviewRate
    expr: rate(client_profile_builder_email_review_status{status="pending"}[1h]) > 10
    for: 1h
    labels:
      severity: warning
    annotations:
      summary: High number of pending email reviews
      description: More than 10 emails pending review for over an hour

  - alert: APIFailureRate
    expr: rate(client_profile_builder_api_calls_total{status="error"}[5m]) > 0.05
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: High API failure rate
      description: External API failure rate is above 5%

dashboards:
  - name: Overview
    panels:
      - title: Request Rate
        type: graph
        metrics:
          - rate(client_profile_builder_requests_total[5m])

      - title: Error Rate
        type: graph
        metrics:
          - rate(client_profile_builder_requests_total{status="error"}[5m])

      - title: Response Time
        type: heatmap
        metrics:
          - rate(client_profile_builder_request_duration_seconds_bucket[5m])

  - name: Business Metrics
    panels:
      - title: Sales Pipeline
        type: gauge
        metrics:
          - client_profile_builder_sales_stage_count

      - title: Email Review Status
        type: pie
        metrics:
          - client_profile_builder_email_review_status

      - title: Processing Success Rate
        type: stat
        metrics:
          - rate(client_profile_builder_emails_processed_total{status="success"}[1h])

logging:
  level: INFO
  handlers:
    - type: file
      filename: logs/app.log
      max_bytes: 10485760  # 10MB
      backup_count: 5
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

    - type: syslog
      address: localhost:514
      facility: local7
      format: '%(name)s[%(process)d]: %(levelname)s %(message)s'

tracing:
  service_name: client_profile_builder
  agent_host: localhost
  agent_port: 6831
  sampler:
    type: const
    param: 1
  tags:
    environment: production 