# Shared State Management Configuration

# Repository settings
repository:
  path: "."
  state_file: "shared_state.json"
  backup_enabled: true
  max_backups: 5

# Environment settings
environments:
  local:
    sync_interval: 60  # 1 minute
    auto_push: true
    notifications: false
    
  cloud:
    sync_interval: 300  # 5 minutes
    auto_push: true
    notifications: true
    
  codex:
    sync_interval: 600  # 10 minutes
    auto_push: true
    notifications: true
    
  github:
    sync_interval: 1800  # 30 minutes
    auto_push: false
    notifications: false

# Analysis configuration
analysis:
  # Code quality analysis
  code_quality:
    enabled: true
    tools:
      - pylint
      - flake8
      - mypy
      - radon
    thresholds:
      complexity: 10
      maintainability: 50
      test_coverage: 80
    auto_fix: true
    
  # Architecture analysis
  architecture:
    enabled: true
    tools:
      - dependency_analyzer
      - complexity_analyzer
      - coupling_analyzer
    thresholds:
      coupling: 0.3
      cohesion: 0.7
      complexity: 0.5
    auto_fix: false
    
  # Security analysis
  security:
    enabled: true
    tools:
      - bandit
      - safety
      - semgrep
    thresholds:
      vulnerability_score: 5
      risk_level: "medium"
    auto_fix: true
    
  # Performance analysis
  performance:
    enabled: true
    tools:
      - cProfile
      - memory_profiler
      - line_profiler
    thresholds:
      response_time: 1000  # ms
      memory_usage: 100  # MB
      cpu_usage: 80  # %
    auto_fix: false
    
  # Documentation analysis
  documentation:
    enabled: true
    tools:
      - pydocstyle
      - docstring_coverage
      - readme_analyzer
    thresholds:
      docstring_coverage: 80
      readme_completeness: 70
    auto_fix: true

# State synchronization
sync:
  # Sync intervals for different operations
  intervals:
    analysis: 3600  # 1 hour
    state_update: 300  # 5 minutes
    cleanup: 86400  # 24 hours
    
  # Retry settings
  retry:
    max_attempts: 3
    delay: 5  # seconds
    backoff_factor: 2
    
  # Conflict resolution
  conflict_resolution:
    strategy: "latest_wins"  # latest_wins, merge, manual
    auto_resolve: true
    notify_on_conflict: true

# Notifications
notifications:
  enabled: true
  channels:
    email:
      enabled: false
      smtp_server: "smtp.gmail.com"
      smtp_port: 587
      username: "${EMAIL_USERNAME}"
      password: "${EMAIL_PASSWORD}"
      recipients: []
      
    slack:
      enabled: false
      webhook_url: "${SLACK_WEBHOOK_URL}"
      channel: "#system-reference"
      
    discord:
      enabled: false
      webhook_url: "${DISCORD_WEBHOOK_URL}"
      
    github:
      enabled: true
      token: "${GITHUB_TOKEN}"
      repository: "Kausiukas/System-Reference"
      
  # Notification triggers
  triggers:
    critical_issue: true
    security_alert: true
    performance_degradation: true
    analysis_complete: false
    state_conflict: true

# Data retention
retention:
  # How long to keep different types of data
  analysis_results: 30  # days
  recommendations: 90  # days
  performance_metrics: 7  # days
  security_alerts: 365  # days
  state_backups: 7  # days
  
  # Cleanup settings
  cleanup:
    enabled: true
    schedule: "daily"
    time: "02:00"  # 2 AM

# Performance monitoring
performance:
  # Metrics to collect
  metrics:
    - response_time
    - memory_usage
    - cpu_usage
    - error_rate
    - throughput
    
  # Thresholds for alerts
  thresholds:
    response_time: 1000  # ms
    memory_usage: 100  # MB
    cpu_usage: 80  # %
    error_rate: 5  # %
    
  # Collection interval
  collection_interval: 60  # seconds

# Security settings
security:
  # Authentication
  authentication:
    enabled: true
    method: "token"  # token, oauth, api_key
    token_env_var: "SHARED_STATE_TOKEN"
    
  # Encryption
  encryption:
    enabled: false
    algorithm: "AES-256"
    key_env_var: "ENCRYPTION_KEY"
    
  # Access control
  access_control:
    read_access: ["local", "cloud", "codex", "github"]
    write_access: ["local", "cloud", "codex"]
    admin_access: ["github"]

# Logging
logging:
  level: "INFO"
  file: "shared_state.log"
  max_size: "10MB"
  backup_count: 5
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Integration settings
integrations:
  # GitHub integration
  github:
    enabled: true
    token: "${GITHUB_TOKEN}"
    repository: "Kausiukas/System-Reference"
    branch: "main"
    auto_commit: true
    auto_push: true
    
  # Streamlit Cloud integration
  streamlit:
    enabled: true
    secrets:
      - "GITHUB_TOKEN"
      - "OPENAI_API_KEY"
      - "SHARED_STATE_TOKEN"
    auto_sync: true
    
  # OpenAI Codex integration
  codex:
    enabled: true
    api_key: "${OPENAI_API_KEY}"
    model: "gpt-4"
    analysis_trigger: "commit"
    auto_analysis: true

# Automated actions
automated_actions:
  # Actions to perform automatically
  actions:
    - name: "code_quality_check"
      trigger: "commit"
      enabled: true
      
    - name: "security_scan"
      trigger: "push"
      enabled: true
      
    - name: "performance_analysis"
      trigger: "deploy"
      enabled: true
      
    - name: "documentation_update"
      trigger: "analysis_complete"
      enabled: false
      
    - name: "automated_fix"
      trigger: "issue_detected"
      enabled: true
      conditions:
        - "issue.priority == 'low'"
        - "auto_fix_available == true"
        
  # Action execution
  execution:
    parallel: true
    max_concurrent: 3
    timeout: 300  # seconds
    retry_failed: true

# Reporting
reporting:
  # Report generation
  reports:
    - name: "daily_summary"
      schedule: "daily"
      time: "09:00"
      format: "markdown"
      
    - name: "weekly_analysis"
      schedule: "weekly"
      day: "monday"
      time: "10:00"
      format: "html"
      
    - name: "monthly_review"
      schedule: "monthly"
      day: 1
      time: "11:00"
      format: "pdf"
      
  # Report delivery
  delivery:
    email: false
    slack: false
    github_issue: true
    file_upload: true

# Error handling
error_handling:
  # Error recovery
  recovery:
    enabled: true
    max_retries: 3
    retry_delay: 5
    
  # Error reporting
  reporting:
    enabled: true
    include_stack_trace: true
    notify_on_error: true
    
  # Graceful degradation
  degradation:
    enabled: true
    fallback_mode: "local_only"
    sync_disabled_on_error: false 